<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="coverlet.collector" Version="6.0.0" />
	<PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
	<PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.11" />
	<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.11" />
	<PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
	<PackageReference Include="Selenium.Support" Version="4.47.0" />
	<PackageReference Include="Selenium.WebDriver" Version="4.47.0" />
	<PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="151.0.7922.13800" />
	<PackageReference Include="xunit" Version="2.5.3" />
	<PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
	<PackageReference Include="Serilog" Version="2.12.0" />
	<PackageReference Include="Serilog.Sinks.File" Version="5.0.0" />
	<PackageReference Include="Serilog.Sinks.Console" Version="4.1.0" />
	  <PackageReference Include="Serilog.Extensions.Logging" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\EpamSeleniumTask.Core\EpamSeleniumTask.Core.csproj" />
	<ProjectReference Include="..\EpamSeleniumTask.Business\EpamSeleniumTask.Business.csproj" />
  </ItemGroup>

  <ItemGroup>
	<None Update="appsettings.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
	<None Update="appsettings.*.json">
	  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</None>
  </ItemGroup>

</Project>
